### PR TITLE
Check for accountUnlockTime attribute before attempting to remove it

### PR DESCRIPTION
**Pull request by csetera**

### CODE REVIEW

**Comment by jrivard** [comment]
This commit contains superfluous changes to other files, including the pom descriptor.  Please send a new request with changes only to the necessary file.

**Comment by GregDomjan** [comment]
Would be nice to have a description in the pull request so that when merged it doesn't show in the tree as "no description provided"

Something like your code comment - 
Only attempt to remove the attribute if it already exists

**Comment by csetera** [comment]
I was, unfortunately, unable to get the code to compile without the pom.xml and override annotation changes that I had added to the pull request.  Are you doing some kind of special setup to allow things to compile targeting Java 5?

**Comment by jrivard** [comment]
It compiles using JDK7 for me just fine, with a target of 1.5.

**Comment by csetera** [comment]
I've rolled back to the version that I forked from Github.

It looks like the compilation will complete with the Override annotations, but I'm still seeing an error relative to the pom.xml:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project ldapchai: Failed to install artifact com.github.ldapchai:ldapchai:extension of your file:optional:0.6.6-SNAPSHOT: /Users/setera/source/thirdparty/ldapchai/target/private/${finalName}- (No such file or directory) -> [Help 1]

This was the error I was seeing that caused me to comment out that section of the POM file.  Is there something I need to set up prior to the Maven build to get beyond this?  I definitely want to do the right things to get your a clean pull request to work with.

**Pull request closed without merging**
